api/urls.py
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet

app_name = "api"

router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename='review')
urlpatterns = router.urls

goodreads/urls.py
import patterns as patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.template.defaulttags import url
from django.urls import path, include, re_path

import os

from books.views import BooksView
from .views import landing_page, home_page, shopping_page, community_page, notice_page, telephone_page

from django.views.static import serve

urlpatterns = [
    path("", landing_page, name="landing_page"),
    path("home/", home_page, name="home_page"),
    path("users/", include("users.urls")),
    path("books/", include("books.urls")),
    path("api/", include("api.urls")),

    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path("shopping/", shopping_page, name="shopping_page"),
    path("community/", community_page, name="community_page"),
    path("notice/", notice_page, name="notice_page"),
    path("telephone/", telephone_page, name="telephone_page"),

    path("", BooksView.as_view(), name="list"),


    # url(r'^media/(?P<path>.*)$', serve,{'document_root':  settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = "users"

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit", ProfileUpdateView.as_view(), name="profile-edit")
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="default_profile_pic.jpg")

users/forms.py
from django import forms
from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})

users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from users.forms import UserCreateForm, UserUpdateForm


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            "form": create_form
        }
        return render(request, "users/register.html", context)
    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
           create_form.save()
           return redirect('users:login')
        else:
            context = {
                "form": create_form
            }
            return render(request, "users/register.html", context)

class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()
        return render(request, "users/login.html",  {"login_form": login_form})

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)

            messages.success(request, "You have succesfully logged in.")

            return redirect("books:list")
        else:
            return render(request, "users/login.html", {"login_form": login_form})

class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "users/profile.html", {"user": request.user})

class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have succesfully logged out.")
        return redirect("landing_page")

class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        return render(request, "users/profile_edit.html", {"form": user_update_form})

    def post(self, request):
        user_update_form = UserUpdateForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES
        )

        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, "You have successfully updated your profile.")

            return redirect("users:profile")

        return render(request, "users/profile_edit.html", {"form": user_update_form})

users/templates/users/login.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Login Page{% endblock %}

{% block content %}
    <head>
        <!--    Stars link -->
        <link rel="stylesheet" type="text/css" href="style.css">

        <!--    Navbar links -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="Colo Shop Template">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="../../../static/coloshop-master/styles/bootstrap4/bootstrap.min.css">
        <link href="../../../static/coloshop-master/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="../../../static/coloshop-master/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
        <link rel="stylesheet" type="text/css" href="../../../static/coloshop-master/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
        <link rel="stylesheet" type="text/css" href="../../../static/coloshop-master/plugins/OwlCarousel2-2.2.1/animate.css">
        <link rel="stylesheet" type="text/css" href="../../../static/coloshop-master/styles/main_styles.css">
        <link rel="stylesheet" type="text/css" href="../../../static/coloshop-master/styles/responsive.css">

         <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css?family=Quicksand:700|Roboto:400,400i,700&display=swap" rel="stylesheet">

        <!-- FontAwesome JS-->
        <script defer src="../../../static/assets/fontawesome/js/all.min.js"></script>

        <!-- Theme CSS -->
        <link id="theme-style" rel="stylesheet" href="../../../static/assets/css/theme.css">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

         <!--    Stars link -->
        <link rel="stylesheet" type="text/css" href="style.css">

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

        <link rel="stylesheet" href="../../../static/bootstrap-footer-11/css/ionicons.min.css">
        <link rel="stylesheet" href="../../../static/bootstrap-footer-11/css/style.css">



        <!-- Login Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="../../../static/login-form-07/fonts/icomoon/style.css">

        <link rel="stylesheet" href="../../../static/login-form-07/css/owl.carousel.min.css">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="../../../static/login-form-07/css/bootstrap.min.css">

        <!-- Style -->
        <link rel="stylesheet" href="../../../static/login-form-07/css/style.css">


    </head>


    <div class="content">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <img src="../../../static/login-form-07/images/undraw_remotely_2j6y.svg" alt="Image" class="img-fluid">
            </div>
            <div class="col-md-6 contents">
              <div class="row justify-content-center">
                <div class="col-md-8">
                  <div class="mb-4">
                  <h3>Kirish</h3>
                  <p class="mb-4">Lorem ipsum dolor sit amet elit. Sapiente sit aut eos consectetur adipisicing.</p>
                </div>
                    <form method="post">
                        {% csrf_token %}
                        {{ login_form | crispy }}

    <!--                    <div class="form-group first login_form.username">-->
    <!--                        <label for="username">Username</label>-->
    <!--                        <input type="text" class="form-control" id="username">-->
    <!--                    </div>-->
    <!--                    <div class="form-group last mb-4 login_form.password">-->
    <!--                        <label for="password">Password</label>-->
    <!--                        <input type="password" class="form-control" id="password">-->
    <!--                    </div>-->


                     <div class="d-flex mb-5 align-items-center">
                        <label class="control control--checkbox mb-0"><span class="caption">Eslab qolish</span>
                          <input type="checkbox" checked="checked"/>
                          <div class="control__indicator"></div>
                        </label>
                        <span class="ml-auto"><a href="#" class="forgot-pass">Parolni unutdingizmi</a></span>
                      </div>

                      <button class="btn btn-block btn-primary {{ login_form.checked }}">Kirish</button><br>
                        <span class="ms-5">Akkauntingiz yuqmi? <a href="{% url 'users:register' %}">Registratsiya</a></span><br><br>

    <!--                  <input type="submit" value="Log In" class="btn btn-block btn-primary">-->

    <!--                  <span class="d-block text-left my-4 text-muted">&mdash; or login with &mdash;</span>-->

                      <div class="social-login ml-5">
                        <a href="#" class="google">
                          <span class="icon-telegram mr-3"></span>
                        </a>
                        <a href="#" class="facebook">
                          <span class="icon-facebook mr-3"></span>
                        </a>
                        <a href="#" class="twitter">
                          <span class="icon-twitter mr-3"></span>
                        </a>
                        <a href="#" class="google">
                          <span class="icon-google mr-3"></span>
                        </a>


                      </div>
                    </form>

    <!--            <form action="#" method="post">-->
    <!--                  <div class="form-group first">-->
    <!--                    <label for="username">Username</label>-->
    <!--                    <input type="text" class="form-control" id="username">-->

    <!--                  </div>-->
    <!--                  <div class="form-group last mb-4">-->
    <!--                    <label for="password">Password</label>-->
    <!--                    <input type="password" class="form-control" id="password">-->

    <!--                  </div>-->

    <!--              <div class="d-flex mb-5 align-items-center">-->
    <!--                <label class="control control&#45;&#45;checkbox mb-0"><span class="caption">Remember me</span>-->
    <!--                  <input type="checkbox" checked="checked"/>-->
    <!--                  <div class="control__indicator"></div>-->
    <!--                </label>-->
    <!--                <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span>-->
    <!--              </div>-->

    <!--              <input type="submit" value="Log In" class="btn btn-block btn-primary">-->

    <!--              <span class="d-block text-left my-4 text-muted">No account? Then, <a href="{% url 'users:register' %}">get registered</a></span>-->

    <!--              <div class="social-login">-->
    <!--                <a href="#" class="facebook">-->
    <!--                  <span class="icon-facebook mr-3"></span>-->
    <!--                </a>-->
    <!--                <a href="#" class="twitter">-->
    <!--                  <span class="icon-twitter mr-3"></span>-->
    <!--                </a>-->
    <!--                <a href="#" class="google">-->
    <!--                  <span class="icon-google mr-3"></span>-->
    <!--                </a>-->
    <!--              </div>-->
    <!--            </form>-->

                </div>
              </div>

            </div>

          </div>
        </div>
    </div>

<!--    <div class="row">-->
<!--        <div class="col-4">-->
<!--            <form method="post">-->
<!--                {% csrf_token %}-->
<!--                {{ login_form | crispy }}-->

<!--                <button class="btn btn-primary">Log in</button> <span class="ms-3">No account? Then, <a href="{% url 'users:register' %}">get registered</a></span>-->
<!--            </form>-->
<!--        </div>-->
<!--    </div>-->



     <!-- Javascript -->
    <script src="../../../static/assets/plugins/popper.min.js"></script>
    <script src="../../../static/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="../../../static/assets/plugins/smoothscroll.min.js"></script>
    <script src="../../../static/assets/js/main.js"></script>


<!-- Login Javascript -->
    <script src="../../../static/login-form-07/js/jquery-3.3.1.min.js"></script>
    <script src="../../../static/login-form-07/js/popper.min.js"></script>
    <script src="../../../static/login-form-07/js/bootstrap.min.js"></script>
    <script src="../../../static/login-form-07/js/main.js"></script>


{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="Colo Shop Template">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="../../../../static/coloshop-master/styles/bootstrap4/bootstrap.min.css">
	<link href="../../../../static/coloshop-master/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type="text/css" href="../../../../static/coloshop-master/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
	<link rel="stylesheet" type="text/css" href="../../../../static/coloshop-master/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
	<link rel="stylesheet" type="text/css" href="../../../../static/coloshop-master/plugins/OwlCarousel2-2.2.1/animate.css">
	<link rel="stylesheet" type="text/css" href="../../../../static/coloshop-master/styles/main_styles.css">
	<link rel="stylesheet" type="text/css" href="../../../../static/coloshop-master/styles/responsive.css">


        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css?family=Quicksand:700|Roboto:400,400i,700&display=swap" rel="stylesheet">

        <!-- FontAwesome JS-->
        <script defer src="../../../../static/assets/fontawesome/js/all.min.js"></script>

        <!-- Theme CSS -->
        <link id="theme-style" rel="stylesheet" href="../../../../static/assets/css/theme.css">

         <!--    Stars link -->
        <link rel="stylesheet" type="text/css" href="style.css">

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

        <link rel="stylesheet" href="../../../../static/bootstrap-footer-11/css/ionicons.min.css">
        <link rel="stylesheet" href="../../../../static/bootstrap-footer-11/css/style.css">

    </head>
<br><br><br>
    <h3>Profilni Taxrirlash</h3>

    <div class="row">
        <div class="col-4">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}

                <button class="btn btn-primary">Saqlash</button>
            </form>
        </div>
    </div>
    <br>

     <!-- Javascript -->
    <script src="../../../static/assets/plugins/popper.min.js"></script>
    <script src="../../../static/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="../../../static/assets/plugins/smoothscroll.min.js"></script>
    <script src="../../../static/assets/js/main.js"></script>


    <script src="../../../../static/coloshop-master/js/jquery-3.2.1.min.js"></script>
    <script src="../../../../static/coloshop-master/styles/bootstrap4/popper.js"></script>
    <script src="../../../../static/coloshop-master/styles/bootstrap4/bootstrap.min.js"></script>
    <script src="../../../../static/coloshop-master/plugins/Isotope/isotope.pkgd.min.js"></script>
    <script src="../../../../static/coloshop-master/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
    <script src="../../../../static/coloshop-master/plugins/easing/easing.js"></script>
    <script src="../../../../static/coloshop-master/js/custom.js"></script>

{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Register Page{% endblock %}

{% block content %}
    <head>
         <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css?family=Quicksand:700|Roboto:400,400i,700&display=swap" rel="stylesheet">

        <!-- FontAwesome JS-->
        <script defer src="../../../static/assets/fontawesome/js/all.min.js"></script>

        <!-- Theme CSS -->
        <link id="theme-style" rel="stylesheet" href="../../../static/assets/css/theme.css">

         <!--    Stars link -->
        <link rel="stylesheet" type="text/css" href="style.css">

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

        <link rel="stylesheet" href="../../../static/bootstrap-footer-11/css/ionicons.min.css">
        <link rel="stylesheet" href="../../../static/bootstrap-footer-11/css/style.css">

    </head>

    <br><br><br>
    <div class="row">
        <div class="col-7 ml-5">
            <img src="../../../static/registratsiya.png" alt="">

        </div>
        <div class="col-4">
            <form method="post" action=" {% url 'users:register' %}" style="">
                {% csrf_token %}

                {{ form | crispy }}

                <button class="btn btn-primary" type="submit">Saqlash</button>
            </form>
        </div>
    </div>











    <br>
     <!-- Javascript -->
    <script src="../../../static/assets/plugins/popper.min.js"></script>
    <script src="../../../static/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="../../../static/assets/plugins/smoothscroll.min.js"></script>
    <script src="../../../static/assets/js/main.js"></script>




{% endblock %}