api/urls.py
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet

app_name = "api"

router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename='review')
urlpatterns = router.urls

books/urls.py
from django.urls import path
from books.views import BooksView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, \
    DeleteReviewView
from goodreads.views import shopping_page

app_name = "books"
urlpatterns = [
    path("", BooksView.as_view(), name="list"),
    path("<int:id>/", BookDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit-review"),
    path(
        "<int:book_id>/reviews/<int:review_id>/delete/confirm/",
         ConfirmDeleteReviewView.as_view(),
        name="confirm-delete-review"
    ),
    path(
        "<int:book_id>/reviews/<int:review_id>/delete/",
         DeleteReviewView.as_view(),
        name="delete-review"
    ),




]

goodreads/urls.py
import patterns as patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.template.defaulttags import url
from django.urls import path, include, re_path

import os

from books.views import BooksView
from .views import landing_page, home_page, shopping_page, community_page, notice_page, telephone_page

from django.views.static import serve

urlpatterns = [
    path("", landing_page, name="landing_page"),
    path("home/", home_page, name="home_page"),
    path("users/", include("users.urls")),
    path("books/", include("books.urls")),
    path("api/", include("api.urls")),

    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),

    path("shopping/", shopping_page, name="shopping_page"),
    path("community/", community_page, name="community_page"),
    path("notice/", notice_page, name="notice_page"),
    path("telephone/", telephone_page, name="telephone_page"),

    path("", BooksView.as_view(), name="list"),


    # url(r'^media/(?P<path>.*)$', serve,{'document_root':  settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

from users.models import CustomUser

class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default="default_cover.jpg")

    def __str__(self):
        return self.title

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def full_name(self):
        return f"{self.first_name} {self.last_name}"


class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    # ++
    # author_picture = models.ImageField(default="author_picture.jpg")



    def __str__(self):
        return f"{self.book.title} by {self.author.first_name} {self.author.last_name}"


class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.stars_given} stars for {self.book.title} by {self.user.username}"

books/forms.py
from django import forms

from books.models import BookReview


class BookReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)



    class Meta:
        model = BookReview
        fields = ('stars_given', 'comment')

books/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from books.forms import BookReviewForm
from books.models import Book, BookReview, Author


class BooksView(View):
    def get(self, request):
        books = Book.objects.all().order_by('id')
        search_query = request.GET.get('q', '')
        if search_query:
            books = books.filter(title__icontains=search_query)

        page_size = request.GET.get('page_size', 4)
        paginator = Paginator(books, page_size)

        page_num = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_num)

        return render(
            request,
            "books/list.html",
            {"page_obj": page_obj, "search_query": search_query}
        )


class BookDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm()

        return render(request, "books/detail.html", {"book": book, "review_form": review_form})

class AddReviewView(LoginRequiredMixin, View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm(data=request.POST)

        if review_form.is_valid():
            BookReview.objects.create(
                book=book,
                user=request.user,
                stars_given=review_form.cleaned_data['stars_given'],
                comment=review_form.cleaned_data['comment']
            )

            return redirect(reverse("books:detail", kwargs={"id": book.id}))

        return render(request, "books/detail.html", {"book": book, "review_form": review_form})



class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review)

        return render(request, "books/edit_review.html", {"book": book, "review": review, "review_form": review_form})


    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)
        review_form = BookReviewForm(instance=review, data=request.POST)

        if review_form.is_valid():
            review_form.save()
            return redirect(reverse("books:detail", kwargs={"id": book_id}))

        return render(request, "books/edit_review.html", {"book": book, "review": review, "review_form": review_form})


class ConfirmDeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)

        return render(request, "books/confirm_delete_review.html", {"book": book, "review": review})


class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.bookreview_set.get(id=review_id)

        review.delete()
        messages.success(request, "You have succesfully deleted this review")

        return redirect(reverse("books:detail", kwargs={"id": book.id}))



# class AuthorView(View):
#     def get(self, request,):
#         author = Author.objects.all().order_by('id')
#         search_query = request.GET.get('q', '')
#         if search_query:
#             author = author.filter(title__icontains=search_query)
#
#         page_size = request.GET.get('page_size', 4)
#         paginator = Paginator(author, page_size)
#
#         page_num = request.GET.get('page', 1)
#         page_obj = paginator.get_page(page_num)
#
#         return render(
#             request,
#             "books/author_list.html",
#             {"page_obj": page_obj, "search_query": search_query}
#         )
#
#
# class AuthorDetailView(View):
#     def get(self, request, id):
#         author = Author.objects.get(id=id)
#
#         return render(request, "books/detail_author.html", {"author": author})
#
#
 

books/templates/books/author_profile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %}

{% block content %}


<section class="section about-section gray-bg" id="about" style="top: -90px">
    <div class="container">
        <div class="row align-items-center flex-row-reverse">
            <div class="col-lg-6">
                <div class="about-text go-to">
                    <h3 class="dark-color">About Me</h3>
                    <h6 class="theme-color lead">A Lead UX &amp; UI designer based in Canada</h6>
                    <p>I design and develop services for customers of all sizes, specializing in creating stylish, modern websites, web services and online stores. My passion is to design digital user experiences through the bold interface and meaningful interactions.</p>
                    <div class="row about-list">
                        <div class="col-md-6">
                            <div class="media">
                                <label>Birthday</label>
                                <p>4th april 1998</p>
                            </div>
                            <div class="media">
                                <label>Age</label>
                                <p>22 Yr</p>
                            </div>
                            <div class="media">
                                <label>Address</label>
                                <p>Canada</p>
                            </div>

                        </div>
                        <div class="col-md-6">
                            <div class="media">
                                <label>E-mail</label>
                                <p>info@domain.com</p>
                            </div>
                            <div class="media">
                                <label>Phone</label>
                                <p>820-885-3321</p>
                            </div>
                            <div class="media">
                                <label>Skype</label>
                                <p>skype.0404</p>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="about-avatar">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" title="" alt="">
                </div>
            </div>
        </div>
        <div class="counter">
            <div class="row">
                <div class="col-6 col-lg-3">
                    <div class="count-data text-center">
                        <h6 class="count h2" data-to="500" data-speed="500">500</h6>
                        <p class="m-0px font-w-600">Happy Clients</p>
                    </div>
                </div>
                <div class="col-6 col-lg-3">
                    <div class="count-data text-center">
                        <h6 class="count h2" data-to="150" data-speed="150">150</h6>
                        <p class="m-0px font-w-600">Project Completed</p>
                    </div>
                </div>
                <div class="col-6 col-lg-3">
                    <div class="count-data text-center">
                        <h6 class="count h2" data-to="850" data-speed="850">850</h6>
                        <p class="m-0px font-w-600">Photo Capture</p>
                    </div>
                </div>
                <div class="col-6 col-lg-3">
                    <div class="count-data text-center">
                        <h6 class="count h2" data-to="190" data-speed="190">190</h6>
                        <p class="m-0px font-w-600">Telephonic Talk</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<br>


{% endblock %}

books/templates/books/confirm_delete_review.html
{% extends 'base.html' %}

{% block title %} Confirm Delete Review {% endblock %}

{% block content %}
    <h3>Are you sure you want to delete this review?</h3>

    <p>
        <b>Book</b>: {{ book.title }}
    </p>
    <p>
        <b>Comment</b>: {{ review.comment }}
    </p>
    <a href="{% url 'books:delete-review' book.id review.id %}" class="btn btn-outline-danger">Yes</a><a href="{% url 'books:detail' book.id %}" class="btn btn-outline-primary">No</a>
{% endblock %}

books/templates/books/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Book Deteil Page{% endblock %}

{% block content %}
    <head>
        <!--    Stars link -->
        <link rel="stylesheet" type="text/css" href="style.css">

        <!--    Navbar links -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="Colo Shop Template">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="../../../static/coloshop-master/styles/bootstrap4/bootstrap.min.css">
        <link href="../../../static/coloshop-master/plugins/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link rel="stylesheet" type="text/css" href="../../../static/coloshop-master/plugins/OwlCarousel2-2.2.1/owl.carousel.css">
        <link rel="stylesheet" type="text/css" href="../../../static/coloshop-master/plugins/OwlCarousel2-2.2.1/owl.theme.default.css">
        <link rel="stylesheet" type="text/css" href="../../../static/coloshop-master/plugins/OwlCarousel2-2.2.1/animate.css">
        <link rel="stylesheet" type="text/css" href="../../../static/coloshop-master/styles/main_styles.css">
        <link rel="stylesheet" type="text/css" href="../../../static/coloshop-master/styles/responsive.css">

         <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css?family=Quicksand:700|Roboto:400,400i,700&display=swap" rel="stylesheet">

        <!-- FontAwesome JS-->
        <script defer src="../../../static/assets/fontawesome/js/all.min.js"></script>

        <!-- Theme CSS -->
        <link id="theme-style" rel="stylesheet" href="../../../static/assets/css/theme.css">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

         <!--    Stars link -->
        <link rel="stylesheet" type="text/css" href="style.css">

        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

        <link rel="stylesheet" href="../../../static/bootstrap-footer-11/css/ionicons.min.css">
        <link rel="stylesheet" href="../../../static/bootstrap-footer-11/css/style.css">

    </head>

    <br><br><br>

    <div class="row mb-4">
        <div class="col-3">
            <img class="cover-pic" src="{{ book.cover_picture.url }}" alt="cover image">
        </div>
        <div class="col-6 ms-5">
            <h3>{{ book.title }}</h3>
            <span class="fst-italic">
                Authored by
                {% for book_author in book.bookauthor_set.all %}
                    {% if forloop.last %}
                          {{ book_author.author.full_name }}
                    {% else %}
                        {{ book_author.author.full_name }},
                    {% endif %}
                {% endfor %}
                <p>
                    {{ book.description }}
                </p>
            </span>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'books:reviews' book.id %}">
                {% csrf_token %}

                {{ review_form | crispy }}

                <button class="btn btn-success">Add review</button>
            </form>

        </div>
    </div>


    {% if book.bookreview_set.exists %}

        <h4>Reviews</h4> <hr>

        {% for review in book.bookreview_set.all %}
            <div class="row mb-3">
                <div class="col-1 me-2">
                    <img class="small-profile-pic" src="{{ review.user.profile_picture.url }}">
                </div>
                <div class="col-7">
                    <b>{{ review.user.username }}</b> rated it {{ review.stars_given }} stars <span class="fw-lighter">{{ review.created_at }}</span>
                    {% if review.user == request.user %}
                        <a href="{% url 'books:edit-review' book.id review.id %}"><i class="bi bi-pen"></i></a>
                        <a href="{% url 'books:confirm-delete-review' book.id review.id %}"><i class="bi bi-trash"></i></a>
                    {% endif %}
                    <p class="mt-2 font-monospace">{{ review.comment }}</p>
                </div>
            </div>
        {% endfor %}
    {% endif %}


    <div class="container">
        <span id="rateMe1"></span>
    </div>
    <!-- rating.js file -->
    <script src="static/js/rating.js"></script>



{% endblock %}

books/templates/books/edit_review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit Review{% endblock %}

{% block content %}
    <h3>Edit Review</h3>

    <div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'books:edit-review' book.id review.id %}">
                {% csrf_token %}

                {{ review_form | crispy }}

                <button class="btn btn-success">Save</button>
            </form>

        </div>
    </div>

{% endblock %}

books/templates/books/list.html
{% extends "base.html" %}

{% block title %}Books Page{% endblock %}

{% block content %}

    <br><br>
    <h1>Sevimli Kitoblar</h1>

<!--    <div class="row mb-3">-->
<!--        <div class="col-4">-->
<!--            <form class="d-flex" method="get">-->
<!--                <input class="form-control me-2" type="text" placeholder="Search" name="q" value="{{ search_query }}">-->

<!--                <button class="btn btn-success">Search</button>-->
<!--            </form>-->

<!--        </div>-->

<!--    </div>-->

    {% if page_obj %}
            {% for book in page_obj.object_list %}
                <div class="row mb-4">
                    <div class="col-3">
                        <img class="cover-pic" src="{{ book.cover_picture.url }}">
                    </div>

                    <div class="col-6 ms-3">
                        <a href="{% url 'books:detail' book.id %}">{{ book.title }}</a>
                        <br>
                        <a href="#">
                             Muallif:
                            {% for book_author in book.bookauthor_set.all %}
                                {% if forloop.last %}
                                      {{ book_author.author.full_name }}
                                {% else %}
                                    {{ book_author.author.full_name }},
                                {% endif %}
                            {% endfor %}
                        </a>

<!--                        <a href="{{ author_detail_page_url }}">-->
<!--                             Authored by-->
<!--                            {% for book_author in book.bookauthor_set.all %}-->
<!--                                {% if forloop.last %}-->
<!--                                      {{ book_author.author.full_name }}-->
<!--                                {% else %}-->
<!--                                    {{ book_author.author.full_name }},-->
<!--                                {% endif %}-->
<!--                            {% endfor %}-->
<!--                        </a>-->
<!--                        Stars html -->
                        <br>
                        <div class="rate">
                            <input type="radio" id="star5" name="rate" value="5" />
                            <label for="star5" title="text">5 stars</label>
                            <input type="radio" id="star4" name="rate" value="4" />
                            <label for="star4" title="text">4 stars</label>
                            <input type="radio" id="star3" name="rate" value="3" />
                            <label for="star3" title="text">3 stars</label>
                            <input type="radio" id="star2" name="rate" value="2" />
                            <label for="star2" title="text">2 stars</label>
                            <input type="radio" id="star1" name="rate" value="1" />
                            <label for="star1" title="text">1 star</label>
                        </div>

                        <!--  End Stars html-->
                        <br><br>
                        <p>
                            {{ book.description }}
                        </p>
                    </div>
                </div>

            {% endfor %}


        <nav>
              <ul class="pagination">
                  {% if page_obj.has_previous %}
                      <li class="page-item"><a class="page-link" href="?page=1">&laquo; Birinchi</a></li>
                      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Oldingi</a></li>
                  {% endif %}

                  <li class="page-item active">
                      <a href="#" class="page-link" >{{ page_obj.number }}</a>
                  </li>


                  {% if page_obj.has_next %}
                      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Keyingi</a></li>
                      <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Oxirgi&raquo;</a></li>
                  {% endif %}
              </ul>
        </nav>
{#        {% if page_obj.has_previous %}#}
{#            <a href="{% url 'books:list' %}?page={{ page_obj.previous_page_number }}">previous</a>#}
{#        {% endif %}#}
{##}
{#        {{ page_obj.number }}#}
{##}
{#        {% if page_obj.has_next %}#}
{#            <a href="{% url 'books:list' %}?page={{ page_obj.next_page_number }}">next</a>#}
{#        {% endif %}#}

    {% else %}
        No books found.
    {% endif %}




{% endblock %}